### ISSUE TITLE
Windows Hello issue on Keepass Startup

### ISSUE THREAD

**Issue by sang0ma** [sirAndros/KeePassWinHello#100]
**Describe the bug**

If the bug has an _error code_ in the message, please include it in **the issue title**.
: Error attached
Integration issue on keepass startup with windows hello

**To Reproduce**

**Expected behavior**

**Screenshots**

"...
Something went wrong. Please report the issue in our Github repository by pressing the "Help" button with the following technical info.
System.NullReferenceException: Object reference not set to an instance of an object.
   at KeePassWinHello.UAC.get_Enabled()
   at KeePassWinHello.UAC.CheckIsCurrentProcessElevated()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at KeePassWinHello.AuthProviderFactory.GetInstance(IntPtr keePassWindowHandle, AuthCacheType authCacheType)
   at KeePassWinHello.KeyCipher.GetAuthProvider(IntPtr keePassWindowHandle)
   at KeePassWinHello.KeyCipher..ctor(IntPtr keePassWindowHandle)
   at KeePassWinHello.KeyManager..ctor(IntPtr windowHandle)
   at KeePassWinHello.KeyManagerProvider.TryInitKeyManager()
..."

## Context

Please complete the following information:

| Component | Version |
|-----------|---------|
| Operating System |  |
| KeePass |  |
| Plugin |  |

**Hardware info**

- PC Motherboard or laptop/tablet model
- Used biometric sensors
- TPM module info (`Win`+`R` => `tpm.msc`)
 
 **Plugin settings**
 
 - [ ] Is persistent mode enabled ("Store keys in Windows Credential Manager" checked)
 
 **KeePass settings and environment**
 
 - [ ] Is secure desktop enabled
 - [ ] Is KeePass running under Administrator (in elevated process)
 - [ ] Was it right after hibernation
 - [ ] Was KeePass minified or closed
 
 - Installed plugins (if any)
 - Any specific settings in KeePass/Plugin

**Additional context**

**Comment by hooddy** [comment]
If I ran KeePass on older Windows version (like Windows 7) it's show me every time error related to Windows Hello and I can not disable it due to absent Windows Hello on Windows 7. In addition on Widows 10 with no activated Windows Hello this settings is kinda useless. I suppose it must be skiped/disabled on start on systems with no Windows Hello or with disabled Windows Hello function on Windows 10 and higher. Please review this issue.
![Безымянный](https://github.com/sirAndros/KeePassWinHello/assets/6899176/fe396223-66a6-4eaf-9fac-5b10146866f2)
![Безымянны2](https://github.com/sirAndros/KeePassWinHello/assets/6899176/6404f327-bbaf-4e39-a72e-7d53b952bd94)
